[colours]

clue = [0, 0, 0, 255]
guess = [0, 0, 0, 255]
candidate = [30, 50, 78, 255]
special_candidate = [25, 1, 98, 255]
rejected_candidate = [255, 0, 0, 255]

border = [0, 0, 0, 255]
big_border = [0, 0, 0, 255]
background = [255, 255, 255, 255]
text = [0, 0, 0, 255]

[sizes]
border = 1
big_border = 3
cell = 60
text = 11

[keybindings]
auto_note = ["Ctrl+A"]
hint = ["Ctrl+H"]
apply_hint = ["Ctrl+O"]
solve = ["Ctrl+S"]
puzzle_menu = ["Ctrl+P"]
remove = ["backspace", "ctrl+backspace"]
reset=["Ctrl+R"]

up = ["w", "k"]
down = ["s", "j"]
left = ["d", "l"]
right = ["a", "h"]

[keybindings.numbers]
1 = ["1", "Num+1"]
2 = ["2", "Num+2"]
3 = ["3", "Num+3"]
4 = ["4", "Num+4"]
5 = ["5", "Num+5"]
6 = ["6", "Num+6"]
7 = ["7", "Num+7"]
8 = ["8", "Num+8"]
9 = ["9", "Num+9"]

# Gameplay settings to use by default
[gameplay]
auto_note = true
start_full = true

# Should not be touched by most users
[developer]
port = 46215
