# Headings must be kept but all key/value pairs are optional 
# Default settings will be used if not set

[colours]
# rgba values
# This example is mostly based on Catppuccin's Frappe palette
clue = [198, 208, 245, 255]
guess = [198, 208, 245, 255]
candidate = [198, 208, 245, 255]

selected = [140, 170, 238, 130]
adjacent = [140, 170, 238, 50]

border = [24, 24, 37, 255]
big_border = [17, 17, 27, 255]

board_background = [65, 69, 89, 255]
menu_background = [98, 104, 128, 255]
button_background = [81, 87, 109, 255]
hint_background = [81, 87, 109, 255]
message_background = [81, 87, 109, 255]
background = [48, 52, 70, 255]

text = [198, 208, 245, 255]
[colours.hint-highlights]
# 1 = [0,0,0,0]

[keybindings]
# Optional but if not set there won't be any way to use those features
# auto_note = ["Ctrl+A"]
# hint = ["Ctrl+H"]
# apply_hint = ["Ctrl+O"]
# solve = ["Ctrl+S"]
# reset=["Ctrl+R"]
#
# up = ["w", "k"]
# down = ["s", "j"]
# left = ["a", "l"]
# right = ["d", "h"]
#
# toggle_mode = ["Ctrl+T"]

[keybindings.numbers]
# 1 = ["1", "Num+1"]
# 2 = ["2", "Num+2"]
# 3 = ["3", "Num+3"]
# 4 = ["4", "Num+4"]
# 5 = ["5", "Num+5"]
# 6 = ["6", "Num+6"]
# 7 = ["7", "Num+7"]
# 8 = ["8", "Num+8"]
# 9 = ["9", "Num+9"]

# Should not be touched by most users
[developer]
# Port should not be used by any other applications
# If it is app won't launch
# port = 46215
